module Listings
where

showTeamNation :: Int -> String
showTeamNation 0 = "Albania"
showTeamNation 1 = "Austria"
showTeamNation 2 = "Belgium"
showTeamNation 3 = "Bulgaria"
showTeamNation 4 = "Croatia"
showTeamNation 5 = "Cyprus"
showTeamNation 6 = "Czech Republic"
showTeamNation 7 = "Denmark"
showTeamNation 8 = "England"
showTeamNation 9 = "9 - Unknown"
showTeamNation 10 = "Estonia"
showTeamNation 11 = "Faroe Islands"
showTeamNation 12 = "Finland"
showTeamNation 13 = "France"
showTeamNation 14 = "Germany"
showTeamNation 15 = "Greece"
showTeamNation 16 = "Hungary"
showTeamNation 17 = "Iceland"
showTeamNation 18 = "Ireland"
showTeamNation 19 = "Israel"
showTeamNation 20 = "Italy"
showTeamNation 21 = "Latvia"
showTeamNation 22 = "Lithuania"
showTeamNation 23 = "Luxembourg"
showTeamNation 24 = "Malta"
showTeamNation 25 = "The Netherlands"
showTeamNation 26 = "Northern Ireland"
showTeamNation 27 = "Norway"
showTeamNation 28 = "Poland"
showTeamNation 29 = "Portugal"
showTeamNation 30 = "Romania"
showTeamNation 31 = "Russia"
showTeamNation 32 = "San Marino"
showTeamNation 33 = "Scotland"
showTeamNation 34 = "Slovenia"
showTeamNation 35 = "Spain"
showTeamNation 36 = "Sweden"
showTeamNation 37 = "Switzerland"
showTeamNation 38 = "Turkey"
showTeamNation 39 = "Ukraine"
showTeamNation 40 = "Wales"
showTeamNation 41 = "Yugoslavia"
showTeamNation 42 = "Algeria"
showTeamNation 43 = "Argentina"
showTeamNation 44 = "Australia"
showTeamNation 45 = "Bolivia"
showTeamNation 46 = "Brazil"
showTeamNation 47 = "47 - Unknown"
showTeamNation 48 = "Chile"
showTeamNation 49 = "Colombia"
showTeamNation 50 = "Ecuador"
showTeamNation 51 = "El Salvador"
showTeamNation 52 = "52 - Unknown"
showTeamNation 53 = "53 - Unknown"
showTeamNation 54 = "54 - Unknown"
showTeamNation 55 = "Japan"
showTeamNation 60 = "Mexico"
showTeamNation 62 = "New Zealand"
showTeamNation 64 = "Paraguay"
showTeamNation 65 = "Peru"
showTeamNation 66 = "Surinam"
showTeamNation 67 = "Taiwan"
showTeamNation 69 = "South Africa"
showTeamNation 71 = "Uruguay"
showTeamNation 73 = "U.S.A."
showTeamNation 75 = "India"
showTeamNation 76 = "Belarus"
showTeamNation 77 = "Venezuela"
showTeamNation 78 = "Slovakia"
showTeamNation 79 = "Ghana"
showTeamNation 80 = "European national"
showTeamNation 81 = "African national"
showTeamNation 82 = "South American national"
showTeamNation 83 = "North American national"
showTeamNation 84 = "Asian national"
showTeamNation 85 = "Oceanian national"
showTeamNation n = show n

data Continent = NorthAmerica
               | SouthAmerica
               | Oceania
               | Africa
               | Asia
               | Europe
               | OtherContinent
  deriving (Ord, Eq)

instance Show Continent where
  show NorthAmerica   = "North America"
  show SouthAmerica   = "South America"
  show Oceania        = "Oceania"
  show Africa         = "Africa"
  show Asia           = "Asia"
  show Europe         = "Europe"
  show OtherContinent = "Other"

countryContinent :: String -> Continent
countryContinent "El Salvador" = NorthAmerica
countryContinent "Mexico" = NorthAmerica
countryContinent "U.S.A." = NorthAmerica
countryContinent "Argentina" = SouthAmerica
countryContinent "Bolivia" = SouthAmerica
countryContinent "Brazil" = SouthAmerica
countryContinent "Chile" = SouthAmerica
countryContinent "Colombia" = SouthAmerica
countryContinent "Ecuador" = SouthAmerica
countryContinent "Paraguay" = SouthAmerica
countryContinent "Peru" = SouthAmerica
countryContinent "Surinam" = SouthAmerica
countryContinent "Uruguay" = SouthAmerica
countryContinent "Venezuela" = SouthAmerica
countryContinent "Australia" = Oceania
countryContinent "New Zealand" = Oceania
countryContinent "India" = Asia
countryContinent "Japan" = Asia
countryContinent "Taiwan" = Asia
countryContinent "Algeria" = Africa
countryContinent "Ghana" = Africa
countryContinent "South Africa" = Africa
countryContinent "Albania" = Europe
countryContinent "Austria" = Europe
countryContinent "Belarus" = Europe
countryContinent "Belgium" = Europe
countryContinent "Bulgaria" = Europe
countryContinent "Croatia" = Europe
countryContinent "Cyprus" = Europe
countryContinent "Czech Republic" = Europe
countryContinent "Denmark" = Europe
countryContinent "England" = Europe
countryContinent "Estonia" = Europe
countryContinent "Faroe Islands" = Europe
countryContinent "Finland" = Europe
countryContinent "France" = Europe
countryContinent "Germany" = Europe
countryContinent "Greece" = Europe
countryContinent "Holland" = Europe
countryContinent "The Netherlands" = Europe
countryContinent "Hungary" = Europe
countryContinent "Iceland" = Europe
countryContinent "Israel" = Europe
countryContinent "Italy" = Europe
countryContinent "Latvia" = Europe
countryContinent "Lithuania" = Europe
countryContinent "Luxembourg" = Europe
countryContinent "Malta" = Europe
countryContinent "Ireland" = Europe
countryContinent "Northern Ireland" = Europe
countryContinent "Norway" = Europe
countryContinent "Poland" = Europe
countryContinent "Portugal" = Europe
countryContinent "Republic Ireland" = Europe
countryContinent "Romania" = Europe
countryContinent "Russia" = Europe
countryContinent "San Marino" = Europe
countryContinent "Scotland" = Europe
countryContinent "Slovakia" = Europe
countryContinent "Slovenia" = Europe
countryContinent "Spain" = Europe
countryContinent "Sweden" = Europe
countryContinent "Switzerland" = Europe
countryContinent "Turkey" = Europe
countryContinent "Ukraine" = Europe
countryContinent "Wales" = Europe
countryContinent "Yugoslavia" = Europe
countryContinent "Bosnia-Herzegovina" = Europe
countryContinent "Serbia" = Europe
countryContinent "Montenegro" = Europe
countryContinent "Kosovo" = Europe
countryContinent "FYR Macedonia" = Europe
countryContinent "Macedonia" = Europe
countryContinent "Azerbaijan" = Europe
countryContinent "Armenia" = Europe
countryContinent "Georgia" = Europe
countryContinent _ = OtherContinent

showDivision :: Int -> String
showDivision 0 = "Premier league"
showDivision 1 = "First league"
showDivision 2 = "Second league"
showDivision 3 = "Third league"
showDivision 4 = "Non-league"
showDivision _ = "Unknown"

showPlayerNation :: Int -> String
showPlayerNation 0 = "Albania"
showPlayerNation 1 = "Austria"
showPlayerNation 2 = "Belgium"
showPlayerNation 3 = "Bulgaria"
showPlayerNation 4 = "Croatia"
showPlayerNation 5 = "Cyprus"
showPlayerNation 6 = "Czech Republic"
showPlayerNation 7 = "Denmark"
showPlayerNation 8 = "England"
showPlayerNation 9 = "Estonia"
showPlayerNation 10 = "Faroe Islands"
showPlayerNation 11 = "Finland"
showPlayerNation 12 = "France"
showPlayerNation 13 = "Germany"
showPlayerNation 14 = "Greece"
showPlayerNation 15 = "Hungary"
showPlayerNation 16 = "Iceland"
showPlayerNation 17 = "Israel"
showPlayerNation 18 = "Italy"
showPlayerNation 19 = "Latvia"
showPlayerNation 20 = "Lithuania"
showPlayerNation 21 = "Luxembourg"
showPlayerNation 22 = "Malta"
showPlayerNation 23 = "The Netherlands"
showPlayerNation 24 = "Northern Ireland"
showPlayerNation 25 = "Norway"
showPlayerNation 26 = "Poland"
showPlayerNation 27 = "Portugal"
showPlayerNation 28 = "Romania"
showPlayerNation 29 = "Russia"
showPlayerNation 30 = "San Marino"
showPlayerNation 31 = "Scotland"
showPlayerNation 32 = "Slovenia"
showPlayerNation 33 = "Sweden"
showPlayerNation 34 = "Turkey"
showPlayerNation 35 = "Ukraine"
showPlayerNation 36 = "Wales"
showPlayerNation 37 = "Serbia"
showPlayerNation 38 = "Belarus"
showPlayerNation 39 = "Slovakia"
showPlayerNation 40 = "Spain"
showPlayerNation 41 = "Armenia"
showPlayerNation 42 = "Bosnia-Herzegovina"
showPlayerNation 43 = "Azerbaijan"
showPlayerNation 44 = "Georgia"
showPlayerNation 45 = "Switzerland"
showPlayerNation 46 = "Ireland"
showPlayerNation 47 = "FYR Macedonia"
showPlayerNation 48 = "Turkmenistan"
showPlayerNation 49 = "Liechtenstein"
showPlayerNation 50 = "Moldova"
showPlayerNation 51 = "Costa Rica"
showPlayerNation 52 = "El Salvador"
showPlayerNation 53 = "Guatemala"
showPlayerNation 54 = "Honduras"
showPlayerNation 55 = "Bahamas"
showPlayerNation 56 = "Mexico"
showPlayerNation 57 = "Panama"
showPlayerNation 58 = "U.S.A."
showPlayerNation 59 = "Bahrain"
showPlayerNation 60 = "Nicaragua"
showPlayerNation 61 = "Bermuda"
showPlayerNation 62 = "Jamaica"
showPlayerNation 63 = "Trinidad and Tobago"
showPlayerNation 64 = "Canada"
showPlayerNation 65 = "Barbados"
showPlayerNation 66 = "El Salvador"
showPlayerNation 67 = "Saint Vincent and the Grenadines"
showPlayerNation 68 = "Argentina"
showPlayerNation 69 = "Bolivia"
showPlayerNation 70 = "Brazil"
showPlayerNation 71 = "Chile"
showPlayerNation 72 = "Colombia"
showPlayerNation 73 = "Ecuador"
showPlayerNation 74 = "Paraguay"
showPlayerNation 75 = "Surinam"
showPlayerNation 76 = "Uruguay"
showPlayerNation 77 = "Venezuela"
showPlayerNation 78 = "Guyana"
showPlayerNation 79 = "Peru"
showPlayerNation 80 = "Algeria"
showPlayerNation 81 = "South Africa"
showPlayerNation 82 = "Botswana"
showPlayerNation 83 = "Burkina Faso"
showPlayerNation 84 = "Burundi"
showPlayerNation 85 = "Lesotho"
showPlayerNation 86 = "Congo"
showPlayerNation 87 = "Zambia"
showPlayerNation 88 = "Ghana"
showPlayerNation 89 = "Senegal"
showPlayerNation 90 = "Ivory Coast"
showPlayerNation 91 = "Tunisia"
showPlayerNation 92 = "Mali"
showPlayerNation 93 = "Madagascar"
showPlayerNation 94 = "Cameroon"
showPlayerNation 95 = "Chad"
showPlayerNation 96 = "Uganda"
showPlayerNation 97 = "Liberia"
showPlayerNation 98 = "Mozambique"
showPlayerNation 99 = "Kenia"
showPlayerNation 100 = "Sudan"
showPlayerNation 101 = "Swaziland"
showPlayerNation 102 = "Angola"
showPlayerNation 103 = "Togo"
showPlayerNation 104 = "Zimbabwe"
showPlayerNation 105 = "Egypt"
showPlayerNation 106 = "Tanzania"
showPlayerNation 107 = "Nigeria"
showPlayerNation 108 = "Ethiopia"
showPlayerNation 109 = "Gabon"
showPlayerNation 110 = "Sierra Leone"
showPlayerNation 111 = "Benin"
showPlayerNation 112 = "Congo"
showPlayerNation 113 = "Guinea"
showPlayerNation 114 = "Sri Lanka"
showPlayerNation 115 = "Morocco"
showPlayerNation 116 = "Gambia"
showPlayerNation 117 = "Malawi"
showPlayerNation 118 = "Japan"
showPlayerNation 119 = "Taiwan"
showPlayerNation 120 = "India"
showPlayerNation 121 = "Bangladesh"
showPlayerNation 122 = "Brunei"
showPlayerNation 123 = "Iraq"
showPlayerNation 124 = "Jordan"
showPlayerNation 125 = "Sri Lanka"
showPlayerNation 126 = "Syria"
showPlayerNation 127 = "South Korea"
showPlayerNation 128 = "Iran"
showPlayerNation 129 = "Vietnam"
showPlayerNation 130 = "Malaysia"
showPlayerNation 131 = "Saudi Arabia"
showPlayerNation 132 = "Yemen"
showPlayerNation 133 = "Kuwait"
showPlayerNation 134 = "Laos"
showPlayerNation 135 = "North Korea"
showPlayerNation 136 = "Oman"
showPlayerNation 137 = "Pakistan"
showPlayerNation 138 = "Philippines"
showPlayerNation 139 = "China"
showPlayerNation 140 = "Singapore"
showPlayerNation 141 = "Mauritius"
showPlayerNation 142 = "Burma"
showPlayerNation 143 = "Papua New Guinea"
showPlayerNation 144 = "Thailand"
showPlayerNation 145 = "Uzbekistan"
showPlayerNation 146 = "Qatar"
showPlayerNation 147 = "United Arab Emirates"
showPlayerNation 148 = "Australia"
showPlayerNation 149 = "New Zealand"
showPlayerNation 150 = "Fiji"
showPlayerNation 151 = "Solomon Islands"
showPlayerNation _   = "Unknown"


